[project]
name = "teiko-technical"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dash>=2.15.0",
    "pytest>=7.4.4",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "black>=23.3.0",
    "ipykernel>=6.16.2",
    "pre-commit>=2.21.0",
    "pytest>=7.4.4",
]

[project.optional-dependencies]
dev = [
    "black[jupyter]",
    "isort",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["data*", "db*", "tests*"]
