name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - run: uv sync --dev

      - run: uv pip install .[dev]

      - run: uv run black --check .

      - run: uv run isort --check-only .

      - run: uv run pytest
